travis:
  secure:
    BINSTAR_TOKEN: oWIy6NNplomWmhduqqKaao6Xk3wQOGu8DtUuNSDkGwgcAXiGWtD7uobq4NYO7gdu8zp0H9vpWHAe0l9MqynwvlPmmZe51cBkmIX9+zj/bhcpA96bjDo+3xZl8lFEJxb4XGYUWxf93fOtXIdtkbZS+/s+Fa+3646ohy5nU9VtuJ3pwwZrNUstg1R1nYKVBDKr4zoQnBUkThTq0z42uNhuW68lPQ9q8hTIX7rEX3ACjo4J5UfPlqm0vjF027puaXisJ2pzuSDwAKbykVzRbU7l/LCWM9D27ri+aPZ8D8IOu4F45DVWrCXszmZhzdT2s7jnlva6CcICHpUrmTf0E5O2k6wjuVCQ8dop+GSsEQX0YK3hfaEMmHnZZGDyBPpGtdc4A/a34OOCDP+Hy/BbiTb3m0QFXCIf+GKEXMGnSwBzyVaic0CdtNh7c+WqpfAumha34RzA4UO2zrfgGmspILTbUNUXtP3M/wn1wh/P6XtS8qVLxctUznxOBHwrIn7o1JdRQSJVhRFxsXqS4da0c6zEDm1vKqSCRzOOmzRQbj5xF5Ja/BMQBzLWjruuAS1+075mEvmR6Y0kM4mYlFRrXdSqJ6NJK7cjp/ZkWQSoyXYloZx7AM1p5snDH+z9LcCWoI528OlaHqm8aiTQUP2CVJlvClMVomhWcS9sSA+603ofNrQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
